name       : kimageannotator
version    : 0.4.0
release    : 1
source     :
    - https://github.com/ksnip/kImageAnnotator/archive/v0.4.0.tar.gz : 4ce8b9853e7c55cffd5eb5fe42ca89ead55db5f432be1b715e6f2804f7e8287d
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Tool for annotating images
description: |
    Tool for annotating images
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(x11)
    - kcolorpicker-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
