name       : kimageannotator
version    : 0.5.3
release    : 4
source     :
    - https://github.com/ksnip/kImageAnnotator/archive/refs/tags/v0.5.3.tar.gz : afb8d93b36dae06c9ccd5cdba1640bcd1d8f06607a2ed9f37f885d491377d5a8
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Tool for annotating images
description: |
    Tool for annotating images
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(x11)
    - kcolorpicker-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
