name       : kimageannotator
version    : 0.4.2
release    : 3
source     :
    - https://github.com/ksnip/kImageAnnotator/archive/refs/tags/v0.4.2.tar.gz : 9e8945d8b5871a1020be643088d15cd76496ad707a1f464af8dd91958b430856
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Tool for annotating images
description: |
    Tool for annotating images
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(x11)
    - kcolorpicker-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
